[licenses]
allow = [
    "Unicode-DFS-2016",
    "MPL-2.0",
]
allow-osi-fsf-free = "both"
exceptions = [
    { allow = [
        "OpenSSL",
    ], name = "ring" },
]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [
   { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "allow"
