[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-3.0",
    "MPL-2.0",
    "ISC",
]
exceptions = [
    { allow = [
        "OpenSSL",
    ], name = "ring" },
]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [
   { path = "LICENSE", hash = 0xbd0eed23 }
]

[bans]
multiple-versions = "allow"
